### ISSUE TITLE
Discovery rule Openstack Endpoints not working by default

### ISSUE THREAD

**Issue by jord-bh** [linuxpolska/zabbix-openstack#7]
Hi,

when tinkering around with the plugin, I encountered a problem whereby none of the endpoint items got discovered automatically. The zabbix web gui claimed that the rule wouldn't work because it was expecting a JSON object response from the script, manually executing the script worked.

On line 67-68 inside server/externalscripts/openstack-discovery two print statements are defined:
```
  print(e)
  print(host)
```

After commenting those out, my controller host had the correct items added.

After looking at other issues in this repo, it seems like other people might be encountering the same issue (see comments on issue #1 )

Is this a known issue or a problem with my zabbix server version? (3.0)

**Comment by tristanlt** [comment]
@cloudowski, my bad, I let some debug statements before the last PR (#6 ).

Sorry for this thoughtlessness

**Comment by cloudowski** [comment]
Ok, so I'm closing it then.
